# nixpacks.toml (Railway Nixpacks 설정)
[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Flask 앱 빌드 완료'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - app:app"

# 또는 Railway 대시보드에서 다음 설정을 직접 입력:

# Start Command:
gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app

# Build Command (비워두거나):
pip install -r requirements.txt

# Root Directory:
/ (또는 비워두기)

# 만약 main.py 파일이 있다면 삭제하거나 이름을 변경하세요:
# main.py -> main_streamlit.py (사용하지 않는 경우)

# .railwayignore 파일 생성 (불필요한 파일 제외)
main.py
*.streamlit*
.streamlit/
__pycache__/
*.pyc
.git/
.gitignore
README.md
docs/