# Streamlit 설정 파일 (Railway 최적화) - 오류 수정 완료
[server]
headless = true
port = 8080
address = "0.0.0.0"
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5000  # 5GB (Railway 메모리 제한 고려)

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[client]
caching = true
displayEnabled = true
showErrorDetails = false  # Railway 보안 최적화

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

# Railway 메모리 최적화 (수정됨)
[global]
# dataFrameSerialization = "legacy"  # 이 라인 제거! (deprecated)
showWarningOnDirectExecution = false
suppressDeprecationWarnings = true