# .streamlit/config.toml - 완전히 정리된 버전

[server]
headless = true
port = 8080
address = "0.0.0.0"
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5000

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

# global 섹션 완전 제거 (문제 해결)